---
name: Arduino_CI

on: [push, pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-platform: ["esp32:esp32"]
        fqbn: ["esp32:esp32:esp32c3:PartitionScheme=huge_app,FlashMode=dio"]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Arduino Cli
        uses: arduino/setup-arduino-cli@v1

      - name: Install Platform
        run: |
          arduino-cli core update-index
          arduino-cli core update-index --additional-urls https://dl.espressif.com/dl/package_esp32_index.json
          arduino-cli core install ${{matrix.arduino-platform}}
          arduino-cli lib install SPIMemory

      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{matrix.fqbn}} ./stage-genie.ino --output-dir ./stage-genie_esp32c3

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: stage-genie_esp32c3
          path: ./stage-genie_esp32c3
          retention-days: 30
