---
name: Arduino_CI

on: [push, pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        fqbn: ["arduino:avr:pro:cpu=8MHzatmega328"]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Arduino Cli
        uses: arduino/setup-arduino-cli@v1

      - name: Install Platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{matrix.arduino-platform}}

      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{matrix.fqbn}} ./stage-genie.ino --output-dir ./stage-genie_promini8mhz

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: stage-genie_promini8mhz
          path: ./stage-genie_promini8mhz
          retention-days: 30
